JNG-4493 Release judo meta expression asm
BlackBeltTechnology/judo-meta-expression-asm pull request #52
Opened 2023-02-27 15:57 UTC by gaborflorian

<table>
<td>
  <a href="https://blackbelt.atlassian.net/browse/JNG-4493" title="JNG-4493" target="_blank"><img alt="Sub-task" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />JNG-4493</a>  Release judo-meta-expression-asm
  </td></table>
  <br />

2023-02-27 16:03 UTC, noherczeg approved these changes

2023-02-28 08:24 UTC, Madmat8 approved these changes

2023-02-28 21:51 UTC, bencegelei requested changes

2023-02-28 21:51 UTC, bencegelei commented on pom.xml
> +                <version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 09:34 UTC, gaborflorian commented on pom.xml
> +                <version>1.2.11</version>
Requested by Robert

2023-03-01 09:35 UTC, gaborflorian commented on pom.xml
> +                <version>1.2.11</version>
Requested by Robert

2023-03-01 09:46 UTC, robertcsakany approved these changes

2023-03-01 11:58 UTC, bencegelei approved these changes

2023-03-09 10:21 UTC, merged